[package]
name = "cityg-api-client"
version = "0.1.0"
license = "MIT"
authors = ["Sabri Haddouche"]
edition.workspace = true

[features]
default = []
debug-api = []

[dependencies]
reqwest = { version = "0.13", default-features = false, features = ["json", "rustls"] }
prost = "0.14"
prost-types = "0.14"
bytes = "1"
thiserror = "2"
cityg-client = { path = "../cityg-client" }
cityg-api-schema = { path = "../cityg-api-schema" }
msphf-orchestrator = { path = "../msphf-orchestrator" }
msphf-core = { path = "../msphf-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tokio = { version = "1.49", features = ["time"] }
ciborium = "0.2"
serde_bytes = "0.11"
pqcrypto-dilithium = "0.5"
pqcrypto-traits = "0.3"

[dev-dependencies]
tokio = { version = "1.49", features = ["macros", "rt-multi-thread"] }
hex = "0.4"
axum = "0.8"
