[package]
name = "cityg-server"
version = "0.1.0"
license = "MIT"
authors = ["Sabri Haddouche"]
edition.workspace = true

[features]
debug-api = []

[dependencies]
cityg-client = { path = "../cityg-client" }
msphf-core = { path = "../msphf-core" }
msphf-orchestrator = { path = "../msphf-orchestrator" }
ciborium = { version = "0.2", features = ["std"] }

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
rand = "0.8"
tempfile = "3.10"
