[package]
name = "msphf-orchestrator"
version = "0.1.0"
license = "MIT"
authors = ["Sabri Haddouche"]
edition = "2024"

[features]
bench-fixtures = []
zkvrf-pq = ["msphf-lb-vrf"]
default = ["zkvrf-pq"]

[dependencies]
anchor-seed = { path = "../anchor-seed" }
cityg-pqc = { path = "../cityg-pqc" }
msphf-core = { path = "../msphf-core" }
msphf-rlwe = { path = "../msphf-rlwe" }
thiserror = "2.0"
ciborium = { version = "0.2", features = ["std"] }
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
rand = "0.10"
rand_core = "0.10"
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
serde_json = "1.0"
hex = "0.4"
base64 = "0.22"
time = { version = "0.3", features = ["formatting", "parsing", "serde"] }
tracing = { version = "0.1", features = ["std"] }
zeroize = { version = "1", features = ["zeroize_derive"] }

msphf-lb-vrf = { path = "../msphf-lb-vrf", optional = true }
capss = { path = "../capss" }
rand_chacha = "0.10"

chacha20poly1305 = { version = "0.10", features = ["std"] }
blake3 = "1.8"
subtle = "2.6"
pqcrypto-kyber = "0.8.1"
smallvec = "1.15.1"
ahash = { version = "0.8", features = ["serde"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pqcrypto-traits = "0.3"
pqcrypto-dilithium = { version = "0.5", default-features = false, features = ["std"] }

[dev-dependencies]
dudect-bencher = "0.6"
cityg-client = { path = "../cityg-client" }
criterion = { version = "0.8", features = ["html_reports"] }
hex-literal = "1.1"

[[bench]]
name = "srx"
harness = false
[[bin]]
name = "cityg-hps-kat"
path = "src/bin/cityg-hps-kat.rs"
