use cityg_api_schema::pb::{
    AcceptEpochRequest, AcceptEpochResponse, FetchMessagesRequest, FetchMessagesResponse,
    GetBundleRequest, GetBundleResponse, RefreshPivotRequest, RefreshPivotResponse,
    SendMessageRequest, SendMessageResponse,
};
use cityg_client::ClientEpochBundle;

use crate::{CitygApiClient, Error};

pub fn is_fs_forward_jump_group_http_error(
    freeze_code: Option<u32>,
    freeze_reason: Option<&str>,
) -> bool {
    freeze_code == Some(9476) || freeze_reason == Some("fs_forward_jump_group")
}

impl CitygApiClient {
    /// Accepts a new epoch bundle generated by a client.
    ///
    /// This is the primary method for publishing a new epoch to the server.
    /// The server will verify the cryptographic proofs and, if valid, store
    /// the bundle and update the group's state.
    ///
    /// # Arguments
    ///
    /// * `bundle` - The client-generated epoch bundle to publish
    ///
    /// # Returns
    ///
    /// An [`AcceptEpochResponse`] containing:
    /// - `we_epoch_id` - The accepted epoch's unique identifier
    /// - `new_root` - The new group root after applying the epoch
    /// - `status` - Acceptance status
    ///
    /// # Errors
    ///
    /// Returns [`Error::Api`] if the server rejects the epoch due to:
    /// - Invalid witness or proof
    /// - Stale parent root (another epoch won the race)
    /// - Duplicate epoch ID
    /// - Group freeze (safety mechanism triggered)
    ///
    /// # Freeze Codes
    ///
    /// Common rejection reasons include:
    /// - **Code 2**: Witness validation failed
    /// - **Code 3**: SPHF verification failed
    /// - **Code 5**: Parent root not found in window
    /// - **Code 7**: Duplicate epoch ID
    ///
    /// See [`docs/protocol/12-error-reference.md`](https://github.com/pwnsdx/cityg/blob/main/docs/protocol/12-error-reference.md) for complete freeze code documentation.
    ///
    /// # Examples
    ///
    /// ```no_run
    /// use cityg_api_client::CitygApiClient;
    /// use cityg_client::ClientEpochBundle;
    ///
    /// # async fn example(bundle: &ClientEpochBundle) -> Result<(), Box<dyn std::error::Error>> {
    /// let client = CitygApiClient::new("http://localhost:8080");
    ///
    /// // Generate an epoch bundle using cityg_client (see cityg-client crate docs)
    /// match client.accept_epoch_bundle(&bundle).await {
    ///     Ok(response) => {
    ///         println!("✓ Epoch accepted: {}", hex::encode(&response.we_epoch_id));
    ///         println!("  New root: {}", hex::encode(&response.new_root));
    ///     }
    ///     Err(e) => {
    ///         eprintln!("✗ Epoch rejected: {}", e);
    ///     }
    /// }
    /// # Ok(())
    /// # }
    /// ```
    pub async fn accept_epoch_bundle(
        &self,
        bundle: &ClientEpochBundle,
    ) -> Result<AcceptEpochResponse, Error> {
        let bytes = bundle.to_cbor()?;
        let request = AcceptEpochRequest { bundle_cbor: bytes };
        self.post_proto("/v1/accept_epoch", request).await
    }

    /// Sends an encrypted message to the server for the specified epoch.
    ///
    /// The message is stored server-side and can be fetched later by any member
    /// of the epoch who possesses the decryption key.
    ///
    /// # Arguments
    ///
    /// * `we_epoch_id` - The target epoch's 32-byte identifier
    /// * `ciphertext` - The encrypted message payload
    /// * `sender` - Optional sender metadata (e.g., authenticated leaf_id)
    ///
    /// # Returns
    ///
    /// A [`SendMessageResponse`] containing:
    /// - `status` - "stored" if successful
    /// - `message_id` - Unique identifier for the stored message
    /// - `timestamp` - Server timestamp when message was stored
    ///
    /// # Examples
    ///
    /// ```no_run
    /// use cityg_api_client::CitygApiClient;
    ///
    /// # async fn example(client: &CitygApiClient, epoch_id: &[u8; 32]) -> Result<(), Box<dyn std::error::Error>> {
    /// let ciphertext = b"encrypted message payload";
    ///
    /// let response = client.send_message(
    ///     epoch_id,
    ///     ciphertext,
    ///     None  // anonymous sender
    /// ).await?;
    ///
    /// println!("Message stored with status: {}", response.status);
    /// # Ok(())
    /// # }
    /// ```
    pub async fn send_message(
        &self,
        we_epoch_id: &[u8; 32],
        ciphertext: &[u8],
        sender: Option<&[u8]>,
    ) -> Result<SendMessageResponse, Error> {
        let request = SendMessageRequest {
            we_epoch_id: we_epoch_id.to_vec(),
            ciphertext: ciphertext.to_vec(),
            sender: sender.unwrap_or_default().to_vec(),
        };
        self.post_proto("/v1/send_message", request).await
    }

    /// Retrieves all messages stored for a specific epoch.
    ///
    /// Returns all messages that were stored using [`send_message`](Self::send_message)
    /// for the given epoch ID.
    ///
    /// # Arguments
    ///
    /// * `we_epoch_id` - The 32-byte witness extraction epoch ID
    /// * `leaf_id` - The caller leaf ID used for authorization and delivery filtering
    ///
    /// # Returns
    ///
    /// A [`FetchMessagesResponse`] containing:
    /// - `messages` - List of stored messages with ciphertext and metadata
    ///
    /// # Examples
    ///
    /// ```no_run
    /// use cityg_api_client::CitygApiClient;
    ///
    /// # async fn example(client: &CitygApiClient, epoch_id: &[u8; 32]) -> Result<(), Box<dyn std::error::Error>> {
    /// let leaf_id = [0u8; 32];
    /// let response = client.fetch_messages(epoch_id, &leaf_id).await?;
    ///
    /// for msg in response.messages {
    ///     println!(
    ///         "Message: {} bytes (sent: {} ms)",
    ///         msg.ciphertext.len(),
    ///         msg.timestamp_ms
    ///     );
    ///     // Decrypt using your epoch key...
    /// }
    /// # Ok(())
    /// # }
    /// ```
    pub async fn fetch_messages(
        &self,
        we_epoch_id: &[u8; 32],
        leaf_id: &[u8; 32],
    ) -> Result<FetchMessagesResponse, Error> {
        let request = FetchMessagesRequest {
            we_epoch_id: we_epoch_id.to_vec(),
            leaf_id: leaf_id.to_vec(),
        };
        self.post_proto("/v1/messages", request).await
    }

    /// Retrieves a stored client epoch bundle by its ID.
    ///
    /// This allows clients to fetch the CBOR-encoded bundle for any epoch
    /// that was previously accepted by the server.
    ///
    /// # Arguments
    ///
    /// * `we_epoch_id` - The 32-byte epoch identifier
    ///
    /// # Returns
    ///
    /// A [`GetBundleResponse`] containing:
    /// - `bundle_cbor` - The complete CBOR-encoded epoch bundle
    ///
    /// # Examples
    ///
    /// ```no_run
    /// use cityg_api_client::CitygApiClient;
    /// use cityg_client::ClientEpochBundle;
    ///
    /// # async fn example(client: &CitygApiClient, epoch_id: &[u8; 32]) -> Result<(), Box<dyn std::error::Error>> {
    /// let response = client.get_bundle(epoch_id).await?;
    ///
    /// // Deserialize the bundle
    /// let bundle = ClientEpochBundle::from_cbor(&response.bundle_cbor)?;
    /// println!("Retrieved bundle for epoch: {}", hex::encode(&bundle.we_epoch_id));
    /// # Ok(())
    /// # }
    /// ```
    pub async fn get_bundle(&self, we_epoch_id: &[u8; 32]) -> Result<GetBundleResponse, Error> {
        let request = GetBundleRequest {
            we_epoch_id: we_epoch_id.to_vec(),
        };
        self.post_proto("/v1/bundle", request).await
    }

    /// Refreshes the pivot for forward secrecy epoch rotation.
    ///
    /// This endpoint triggers automatic pivot rotation based on the forward
    /// secrecy policy. It should be called periodically (e.g., every hour)
    /// to maintain forward secrecy guarantees.
    ///
    /// # Arguments
    ///
    /// * `bundle` - A client epoch bundle containing the new pivot commitment
    ///
    /// # Examples
    ///
    /// ```no_run
    /// use cityg_api_client::CitygApiClient;
    /// use cityg_client::ClientEpochBundle;
    ///
    /// # async fn example(client: &CitygApiClient, bundle: &ClientEpochBundle) -> Result<(), Box<dyn std::error::Error>> {
    /// // Generate fresh pivot bundle (implementation not shown)
    ///
    /// client.refresh_pivot(&bundle).await?;
    /// println!("Pivot refreshed for forward secrecy");
    /// # Ok(())
    /// # }
    /// ```
    pub async fn refresh_pivot(&self, bundle: &ClientEpochBundle) -> Result<(), Error> {
        let bytes = bundle.to_cbor()?;
        let request = RefreshPivotRequest { bundle_cbor: bytes };
        self.post_proto::<RefreshPivotResponse>("/v1/pivot/refresh", request)
            .await
            .map(|_| ())
    }
}
