#!/bin/bash
set -euo pipefail

# Bootstraps a room via the CityG API using a ML-KEM public key.
# Usage:
#   ./scripts/bootstrap_room.sh <server_url> <room_id> [kbroad_public_key_path]
#
# Defaults:
# - kbroad_public_key_path: macOS/Linux demo key path generated by cityg-client demo helpers
#
# Requirements:
# - curl
# - dd

SERVER_URL="${1:-}"
ROOM_ID="${2:-}"
KEY_PATH="${3:-}"
ADMIN_TOKEN="${CITYG_CLIENT_ADMIN_TOKEN:-${CITYG_SERVER_ROOMS_ADMIN_TOKEN:-}}"

if [ -z "$SERVER_URL" ] || [ -z "$ROOM_ID" ]; then
    echo "usage: ./scripts/bootstrap_room.sh <server_url> <room_id> [kbroad_public_key_path]" >&2
    exit 2
fi

if [ -z "$KEY_PATH" ]; then
    if [ -f "$HOME/Library/Application Support/cityg/demo-kbroad.key" ]; then
        KEY_PATH="$HOME/Library/Application Support/cityg/demo-kbroad.key"
    elif [ -f "$HOME/.config/cityg/demo-kbroad.key" ]; then
        KEY_PATH="$HOME/.config/cityg/demo-kbroad.key"
    else
        echo "error: could not locate demo-kbroad.key; pass an explicit kbroad_public_key_path" >&2
        exit 2
    fi
fi

if [ -z "$ADMIN_TOKEN" ]; then
    echo "error: CITYG_CLIENT_ADMIN_TOKEN or CITYG_SERVER_ROOMS_ADMIN_TOKEN must be set" >&2
    exit 2
fi

if ! command -v curl >/dev/null 2>&1; then
    echo "error: curl is required" >&2
    exit 2
fi

if ! [[ "$ROOM_ID" =~ ^[0-9a-fA-F]{64}$ ]]; then
    echo "error: room_id must be 32-byte lowercase/uppercase hex (64 chars)" >&2
    exit 2
fi

TMP_PUB="$(mktemp)"
TMP_REQ="$(mktemp)"
cleanup() {
    rm -f "$TMP_PUB" "$TMP_REQ"
}
trap cleanup EXIT

# BootstrapRoomRequest:
#   field 1 => room_id (tag 0x0a, len 0x40, 64 ASCII hex chars)
#   field 2 => kbroad_public (tag 0x12, len 1184 => varint a0 09)
dd if="$KEY_PATH" of="$TMP_PUB" bs=1184 count=1 status=none
printf '\x0a\x40' >"$TMP_REQ"
printf '%s' "$ROOM_ID" >>"$TMP_REQ"
printf '\x12\xa0\x09' >>"$TMP_REQ"
cat "$TMP_PUB" >>"$TMP_REQ"

curl -fsS -X POST \
    -H 'content-type: application/x-protobuf' \
    -H "x-cityg-admin-token: ${ADMIN_TOKEN}" \
    --data-binary @"$TMP_REQ" \
    "${SERVER_URL%/}/v1/rooms/bootstrap" >/dev/null

echo "bootstrapped room ${ROOM_ID} at ${SERVER_URL%/}"
