use super::barrier_merge_prepare_runtime::{
    PreparedBarrierMergeExecution, prepare_barrier_merge_execution,
};
use super::barrier_merge_publish_runtime::{
    BarrierMergePublishInputs, BarrierMergePublishPolicy, publish_barrier_merge,
};
use super::*;
use cityg_client::barrier_orchestration::{
    BarrierOrchestrationInputs, prepare_barrier_orchestration,
};

pub(super) async fn perform_barrier_merge_inner(
    request: LeaveRequest,
    mode: BarrierMergeMode,
    allow_pending_recovery: bool,
) -> Result<PublishedBarrierMerge> {
    let PreparedBarrierMergeExecution {
        persist_request,
        client,
        gid,
        barrier_version,
        next_barrier_version,
        fs_ec,
        fs_epoch_commit,
        fs_dev_prev_commit,
        k_fs_current,
        forward_state,
        fs_forward_leap_policy,
        last_accepted_ec,
        header,
        cat_arr,
        parent_root_arr,
        join_delta_root_arr,
        revoked_since_root_arr,
        revoked_root_arr,
        tswe_salt_hash_arr,
        pox_r_commit_arr,
        pop_public_key,
        pop_secret_key,
        vrf_secret_key,
        vrf_public_key,
        msphf_crs_id,
        msphf_params_id,
        proof_mode,
        vrf_id,
        policy_version,
        fs_policy_version,
        fs_epoch_base_ts,
        parities,
        witness_bytes,
        pivot,
        snapshot_hash,
        committed_revocation_roots_hash,
        revocation_roots_hash,
        ticket_history_commitment,
        ticket_history_authority_extension,
        current_global_history_attestation_bytes,
        barrier_update,
    } = prepare_barrier_merge_execution(request, mode, allow_pending_recovery).await?;

    let pop_secret =
        Box::new(dilithium5::SecretKey::from_bytes(&pop_secret_key).context("invalid POP key")?);

    let prepared_orchestration = prepare_barrier_orchestration(BarrierOrchestrationInputs {
        gid: &gid,
        cat: &cat_arr,
        tswe_salt_hash: &tswe_salt_hash_arr,
        parent_root: &parent_root_arr,
        join_delta_root: &join_delta_root_arr,
        revoked_since_root: &revoked_since_root_arr,
        revoked_root: &revoked_root_arr,
        pox_r_commit: &pox_r_commit_arr,
        msphf_crs_id: msphf_crs_id.as_str(),
        msphf_params_id: msphf_params_id.as_str(),
        srx: None,
        pop_public_key: pop_public_key.as_slice(),
        pop_secret_key: pop_secret.as_ref(),
        proof_mode: proof_mode.as_str(),
        vrf_id: vrf_id.as_str(),
        policy_version: policy_version.as_str(),
        vrf_secret_key: vrf_secret_key.as_slice(),
        vrf_public_key: vrf_public_key.as_slice(),
        fs_policy_version: fs_policy_version.as_str(),
        fs_epoch_base_ts,
        barrier_version: next_barrier_version,
        fs_join: FsJoinInputs {
            fs_ec,
            fs_epoch_commit,
            fs_dev_prev_commit,
        },
    });

    publish_barrier_merge(BarrierMergePublishInputs {
        policy: BarrierMergePublishPolicy {
            pending_barrier_update_reason: mode.reason(),
            build_barrier_update_reason: mode.reason(),
            current_k_fs: mode.reseeds_k_fs().then_some(&k_fs_current),
            build_bundle_context: mode.build_bundle_context(),
            accept_bundle_context: mode.accept_bundle_context(),
            retry_on_fs_forward_jump_group: true,
            trigger_before_publish_join_finalize_fault: mode == BarrierMergeMode::JoinFinalize,
        },
        client: &client,
        persist_request: &persist_request,
        gid: &gid,
        barrier_version,
        next_barrier_version,
        fs_ec,
        fs_dev_prev_commit,
        header,
        cat_arr,
        parent_root_arr,
        params: prepared_orchestration.params,
        parts: prepared_orchestration.parts,
        parities: &parities,
        witness_bytes: witness_bytes.as_deref(),
        pivot: &pivot,
        snapshot_hash,
        committed_revocation_roots_hash,
        revocation_roots_hash,
        ticket_history_commitment,
        ticket_history_authority_extension,
        current_global_history_attestation_bytes,
        barrier_update,
        forward_state,
        fs_forward_leap_policy,
        last_accepted_ec,
    })
    .await
}
