use super::barrier_merge_ticket_runtime::PreparedBarrierMergeTicket;
use super::*;
use cityg_api_client::{
    BarrierSnapshotPreparationRequest, HistoryAuthorityDescriptor, PreparedBarrierSnapshot,
};

pub(super) struct PreparedBarrierMergeSnapshot {
    pub(super) header: BTreeMap<u64, Value>,
    pub(super) cat_arr: [u8; 32],
    pub(super) parent_root_arr: [u8; 32],
    pub(super) join_delta_root_arr: [u8; 32],
    pub(super) revoked_since_root_arr: [u8; 32],
    pub(super) revoked_root_arr: [u8; 32],
    pub(super) tswe_salt_hash_arr: [u8; 32],
    pub(super) pox_r_commit_arr: [u8; 32],
    pub(super) pivot: PivotParity,
    pub(super) snapshot_hash: [u8; 32],
    pub(super) committed_revocation_roots_hash: [u8; 32],
    pub(super) revocation_roots_hash: [u8; 32],
    pub(super) barrier_update: BarrierUpdateBuildResult,
}

pub(super) struct BarrierSnapshotRuntimeRequest<'a> {
    pub(super) client: &'a CitygApiClient,
    pub(super) room_id: &'a str,
    pub(super) gid: &'a [u8; 32],
    pub(super) leaf_id: &'a [u8; 32],
    pub(super) barrier_version: u64,
    pub(super) cover_leaf_index: u64,
    pub(super) snapshot_hash: [u8; 32],
    pub(super) barrier_n_max: u64,
    pub(super) max_barrier_update_bytes: u64,
    pub(super) header: BTreeMap<u64, Value>,
    pub(super) parities: &'a [PivotParity],
    pub(super) cat: &'a [u8],
    pub(super) pox_r_commit: &'a [u8],
    pub(super) parent_root: &'a [u8],
    pub(super) join_delta_root: &'a [u8],
    pub(super) revoked_since_root: &'a [u8],
    pub(super) revoked_root: &'a [u8],
    pub(super) tswe_salt_hash: &'a [u8],
    pub(super) ticket_history_commitment: &'a HistoryCommitment,
    pub(super) ticket_history_authority_extension: Option<HistoryAuthorityExtension>,
    pub(super) history_authority: Option<HistoryAuthorityDescriptor>,
    pub(super) current_global_history_attestation_bytes: &'a [u8],
    pub(super) merge_ticket_artifact_bytes: &'a [u8],
    pub(super) deployment_profile_manifest_bytes: &'a [u8],
    pub(super) pop_secret_key: &'a [u8],
    pub(super) full_verification_target_leaf_id: Option<[u8; 32]>,
}

pub(super) async fn prepare_barrier_merge_snapshot(
    ticket: &PreparedBarrierMergeTicket,
    mode: BarrierMergeMode,
) -> Result<PreparedBarrierMergeSnapshot> {
    prepare_barrier_snapshot_runtime(
        BarrierSnapshotRuntimeRequest {
            client: &ticket.client,
            room_id: ticket.room_id.as_str(),
            gid: &ticket.gid,
            leaf_id: &ticket.leaf_id,
            barrier_version: ticket.barrier_version,
            cover_leaf_index: ticket.cover_leaf_index,
            snapshot_hash: ticket.snapshot_hash,
            barrier_n_max: ticket.barrier_n_max,
            max_barrier_update_bytes: ticket.max_barrier_update_bytes,
            header: ticket.header.clone(),
            parities: &ticket.parities,
            cat: &ticket.cat,
            pox_r_commit: &ticket.pox_r_commit,
            parent_root: &ticket.parent_root,
            join_delta_root: &ticket.join_delta_root,
            revoked_since_root: &ticket.revoked_since_root,
            revoked_root: &ticket.revoked_root,
            tswe_salt_hash: &ticket.tswe_salt_hash,
            ticket_history_commitment: &ticket.ticket_history_commitment,
            ticket_history_authority_extension: ticket.ticket_history_authority_extension,
            history_authority: ticket.history_authority.clone(),
            current_global_history_attestation_bytes: ticket
                .current_global_history_attestation_bytes
                .as_slice(),
            merge_ticket_artifact_bytes: ticket.merge_ticket_artifact_bytes.as_slice(),
            deployment_profile_manifest_bytes: ticket.deployment_profile_manifest_bytes.as_slice(),
            pop_secret_key: ticket.pop_secret_key.as_slice(),
            full_verification_target_leaf_id: None,
        },
        mode.reason(),
        mode.label(),
    )
    .await
}

pub(super) async fn prepare_barrier_snapshot_runtime(
    request: BarrierSnapshotRuntimeRequest<'_>,
    barrier_update_reason: u64,
    operation_label: &str,
) -> Result<PreparedBarrierMergeSnapshot> {
    let BarrierSnapshotRuntimeRequest {
        client,
        room_id,
        gid,
        leaf_id,
        barrier_version,
        cover_leaf_index,
        snapshot_hash,
        barrier_n_max,
        max_barrier_update_bytes,
        header,
        parities,
        cat,
        pox_r_commit,
        parent_root,
        join_delta_root,
        revoked_since_root,
        revoked_root,
        tswe_salt_hash,
        ticket_history_commitment,
        ticket_history_authority_extension,
        history_authority,
        current_global_history_attestation_bytes,
        merge_ticket_artifact_bytes,
        deployment_profile_manifest_bytes,
        pop_secret_key,
        full_verification_target_leaf_id,
    } = request;

    let PreparedBarrierSnapshot {
        header,
        cat: cat_arr,
        parent_root: parent_root_arr,
        join_delta_root: join_delta_root_arr,
        revoked_since_root: revoked_since_root_arr,
        revoked_root: revoked_root_arr,
        tswe_salt_hash: tswe_salt_hash_arr,
        pox_r_commit: pox_r_commit_arr,
        pivot,
        snapshot_hash,
        committed_revocation_roots_hash,
        revocation_roots_hash,
        barrier_update,
    } = client
        .barrier_prepare_snapshot(BarrierSnapshotPreparationRequest {
            room_id,
            gid,
            leaf_id,
            barrier_version,
            cover_leaf_index,
            snapshot_hash,
            barrier_n_max,
            max_barrier_update_bytes,
            header,
            parities,
            cat,
            pox_r_commit,
            parent_root,
            join_delta_root,
            revoked_since_root,
            revoked_root,
            tswe_salt_hash,
            ticket_history_commitment,
            ticket_history_authority_extension,
            history_authority,
            current_global_history_attestation_bytes,
            merge_ticket_artifact_bytes,
            deployment_profile_manifest_bytes,
            pop_secret_key,
            full_verification_target_leaf_id,
            barrier_update_reason,
            operation_label,
        })
        .await
        .map_err(anyhow::Error::from)?;
    let barrier_update = BarrierUpdateBuildResult::from_core(barrier_n_max, barrier_update);

    Ok(PreparedBarrierMergeSnapshot {
        header,
        cat_arr,
        parent_root_arr,
        join_delta_root_arr,
        revoked_since_root_arr,
        revoked_root_arr,
        tswe_salt_hash_arr,
        pox_r_commit_arr,
        pivot,
        snapshot_hash,
        committed_revocation_roots_hash,
        revocation_roots_hash,
        barrier_update,
    })
}
